// Mock data for frontend functionality

export const mockMembers = [
  {
    id: 1,
    name: "Luxury Hotel Kathmandu",
    email: "contact@luxuryhotel.com",
    phone: "+977 9841234567",
    organization: "Kalanki Hotel Business Association",
    status: "active",
    joinDate: "2024-01-15",
    address: "Thamel, Kathmandu",
    contactPerson: "Rajesh Kumar",
  },
  {
    id: 2,
    name: "Resort Kathmandu Luxury",
    email: "info@resortkathm.com",
    phone: "+977 9851234568",
    organization: "Balaju Hotel Business Association",
    status: "active",
    joinDate: "2024-02-20",
    address: "Balaju, Kathmandu",
    contactPerson: "Sita Sharma",
  },
  {
    id: 3,
    name: "Traditional Nepalese Hotel",
    email: "hello@traditional.com",
    phone: "+977 9861234569",
    organization: "Sundhara Hotel Business Association",
    status: "pending",
    joinDate: "2024-11-10",
    address: "Sundhara, Kathmandu",
    contactPerson: "Amit Thapa",
  },
  {
    id: 4,
    name: "Hotel Excellence",
    email: "contact@excellence.com",
    phone: "+977 9871234570",
    organization: "Kalanki Hotel Business Association",
    status: "active",
    joinDate: "2023-08-05",
    address: "Kalanki, Kathmandu",
    contactPerson: "Priya Gurung",
  },
  {
    id: 5,
    name: "Bhaktapur Resort Scenic",
    email: "info@bhaktapurresort.com",
    phone: "+977 9881234571",
    organization: "Koteshwor Hotel Business Association",
    status: "inactive",
    joinDate: "2023-05-12",
    address: "Bhaktapur",
    contactPerson: "Rohan Malla",
  },
]

export const mockOrganizations = [
  {
    id: 1,
    name: "Kalanki Hotel Business Association",
    location: "Kalanki, Kathmandu",
    memberCount: 45,
    president: "Ram Bahadur Shrestha",
    established: "2018",
    description: "Leading hotel association in Kalanki area",
  },
  {
    id: 2,
    name: "Sundhara Hotel Business Association",
    location: "Sundhara, Kathmandu",
    memberCount: 38,
    president: "Laxmi Devi Maharjan",
    established: "2017",
    description: "Promoting hospitality excellence in Sundhara",
  },
  {
    id: 3,
    name: "Bagbazar Hotel Business Association",
    location: "Bagbazar, Kathmandu",
    memberCount: 32,
    president: "Krishna Prasad Adhikari",
    established: "2019",
    description: "Supporting hotels in Bagbazar region",
  },
  {
    id: 4,
    name: "Koteshwor Hotel Business Association",
    location: "Koteshwor, Kathmandu",
    memberCount: 41,
    president: "Sunita Rai",
    established: "2018",
    description: "Koteshwor area hotel network",
  },
  {
    id: 5,
    name: "Airport Hotel Business Association",
    location: "Airport Area, Kathmandu",
    memberCount: 28,
    president: "Bikram Thapa",
    established: "2020",
    description: "Hotels near Tribhuvan International Airport",
  },
  {
    id: 6,
    name: "Chabahil Hotel Business Association",
    location: "Chabahil, Kathmandu",
    memberCount: 35,
    president: "Anjali Shakya",
    established: "2019",
    description: "Chabahil hospitality community",
  },
  {
    id: 7,
    name: "Balaju Hotel Business Association",
    location: "Balaju, Kathmandu",
    memberCount: 28,
    president: "Deepak Karki",
    established: "2021",
    description: "New Bus Park area hotels",
  },
]

export const mockJobs = [
  {
    id: 1,
    title: "Hotel Manager",
    company: "Luxury Hotel Kathmandu",
    location: "Thamel, Kathmandu",
    salary: "NPR 80,000 - 120,000",
    type: "Full-time",
    experience: "5+ years",
    status: "active",
    postedDate: "2025-01-10",
    applicants: 45,
    views: 320,
  },
  {
    id: 2,
    title: "Front Desk Supervisor",
    company: "Resort Kathmandu Luxury",
    location: "Balaju, Kathmandu",
    salary: "NPR 40,000 - 60,000",
    type: "Full-time",
    experience: "3+ years",
    status: "active",
    postedDate: "2025-01-08",
    applicants: 28,
    views: 156,
  },
  {
    id: 3,
    title: "Executive Chef",
    company: "Traditional Nepalese Hotel",
    location: "Sundhara, Kathmandu",
    salary: "NPR 70,000 - 100,000",
    type: "Full-time",
    experience: "7+ years",
    status: "pending",
    postedDate: "2025-01-05",
    applicants: 12,
    views: 89,
  },
]

export const mockEvents = [
  {
    id: 1,
    title: "Annual General Meeting 2025",
    date: "2025-02-15",
    time: "10:00 AM",
    location: "Hotel Yak & Yeti, Kathmandu",
    capacity: 200,
    registered: 145,
    status: "upcoming",
    description: "Annual meeting of all DHBA members",
    organizer: "DHBA Admin",
  },
  {
    id: 2,
    title: "Tourism Workshop",
    date: "2025-02-22",
    time: "2:00 PM",
    location: "Soaltee Hotel, Kathmandu",
    capacity: 100,
    registered: 67,
    status: "upcoming",
    description: "Workshop on sustainable tourism practices",
    organizer: "Training Committee",
  },
  {
    id: 3,
    title: "Networking Dinner",
    date: "2025-03-05",
    time: "7:00 PM",
    location: "Hyatt Regency, Kathmandu",
    capacity: 150,
    registered: 89,
    status: "upcoming",
    description: "Networking event for hospitality professionals",
    organizer: "DHBA Admin",
  },
]

export const mockBlogPosts = [
  {
    id: 1,
    title: "Best Practices in Hotel Management",
    excerpt: "Learn the latest strategies for effective hotel management",
    author: "Rajesh Kumar",
    date: "2025-01-10",
    category: "Management",
    status: "published",
    views: 1250,
  },
  {
    id: 2,
    title: "Tourism Industry Growth in Nepal",
    excerpt: "Analysis of tourism trends and opportunities",
    author: "Sita Sharma",
    date: "2025-01-05",
    category: "Industry Insights",
    status: "published",
    views: 980,
  },
  {
    id: 3,
    title: "Customer Service Excellence",
    excerpt: "Master the art of exceptional customer service",
    author: "Amit Thapa",
    date: "2024-12-28",
    category: "Training",
    status: "draft",
    views: 0,
  },
]

export const mockActivityLog = [
  {
    id: 1,
    action: "New member registered",
    user: "Luxury Hotel Kathmandu",
    details: "Joined Kalanki Hotel Business Association",
    timestamp: "2 hours ago",
    type: "member",
  },
  {
    id: 2,
    action: "Job posted",
    user: "Resort Kathmandu",
    details: "Front Desk Supervisor position",
    timestamp: "5 hours ago",
    type: "job",
  },
  {
    id: 3,
    action: "Event created",
    user: "Admin",
    details: "Annual General Meeting 2025",
    timestamp: "1 day ago",
    type: "event",
  },
  {
    id: 4,
    action: "Blog published",
    user: "Content Team",
    details: "Best Practices in Hotel Management",
    timestamp: "2 days ago",
    type: "content",
  },
  {
    id: 5,
    action: "Member approved",
    user: "Admin",
    details: "Hotel Excellence membership approved",
    timestamp: "3 days ago",
    type: "member",
  },
]

export const mockGalleryPhotos = [
  {
    id: 1,
    title: "Luxury Hotel Kathmandu",
    url: "/luxury-hotel-kathmandu.jpg",
    category: "hotels",
    uploadedBy: "Admin",
    uploadDate: "2025-01-15",
  },
  {
    id: 2,
    title: "Hotel Lobby",
    url: "/luxury-hotel-lobby.png",
    category: "hotels",
    uploadedBy: "Admin",
    uploadDate: "2025-01-14",
  },
]

export const mockGalleryVideos = [
  {
    id: 1,
    title: "Hospitality Excellence in Nepal",
    videoId: "oerd3LVEyPs",
    thumbnail: "/luxury-hotel-lobby.png",
    category: "promotional",
    duration: "3:45",
    uploadedBy: "Admin",
    uploadDate: "2025-01-12",
  },
]

export const mockResources = [
  {
    id: 1,
    title: "Annual Tourism Report 2024",
    type: "PDF",
    category: "Reports",
    size: "2.5 MB",
    downloads: 145,
    date: "2025-01-15",
    description: "Comprehensive report on tourism statistics and trends for 2024."
  },
  {
    id: 2,
    title: "Hotel Safety Guidelines",
    type: "PDF",
    category: "Guidelines",
    size: "1.2 MB",
    downloads: 89,
    date: "2024-12-10",
    description: "Standard safety protocols for hotels and resorts."
  },
  {
    id: 3,
    title: "Membership Application Form",
    type: "DOC",
    category: "Forms",
    size: "500 KB",
    downloads: 210,
    date: "2024-11-20",
    description: "Application form for new member registration."
  },
]

export const mockMessages = [
  {
    id: 1,
    sender: "Luxury Hotel Kathmandu",
    subject: "Inquiry about membership renewal",
    preview: "Hi, I would like to know the process for renewing our membership...",
    date: "2 hours ago",
    read: false,
    avatar: "L"
  },
  {
    id: 2,
    sender: "Resort Kathmandu",
    subject: "Event sponsorship opportunity",
    preview: "We are interested in sponsoring the upcoming Annual General Meeting...",
    date: "1 day ago",
    read: true,
    avatar: "R"
  },
  {
    id: 3,
    sender: "Amit Thapa",
    subject: "Feedback on recent workshop",
    preview: "The tourism workshop was very informative. I have some suggestions...",
    date: "2 days ago",
    read: true,
    avatar: "A"
  },
]
